version: 2
updates:

- package-ecosystem: "bundler"
  directory: "/"
  schedule:
    interval: "daily"

- package-manager: "javascript"
  directory: "/"
  schedule:
    interval: "daily"

- package-manager: "javascript"
  directory: "/node_modules/reveal.js/"
  schedule:
    interval: "daily"
    
- package-manager: "javascript"
  directory: "/node_modules/reveal.js/plugin/multiplex/"
  schedule:
    interval: "daily"
