version: 2
updates:

- package-ecosystem: "bundler"
  directory: "/"
  schedule:
    interval: "daily"
  allow:
    - dependency-type: "all"

- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
  allow:
    - dependency-type: "all"    

- package-ecosystem: "npm"
  directory: "/node_modules/reveal.js/"
  schedule:
    interval: "daily"
  allow:
    - dependency-type: "all"
    
- package-ecosystem: "npm"
  directory: "/node_modules/reveal.js/plugin/multiplex/"
  schedule:
    interval: "daily"
  allow:
    - dependency-type: "all"
