version: 2
updates:

- package-ecosystem: "bundler"
  directory: "/"
  schedule:
    interval: "daily"

- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"

- package-ecosystem: "npm"
  directory: "/node_modules/reveal.js/package.json"
  schedule:
    interval: "daily"
    
- package-ecosystem: "npm"
  directory: "/node_modules/reveal.js/plugin/multiplex/package.json"
  schedule:
    interval: "daily"
