name: "Dependabot Automerge"

on: pull_request

jobs:
  auto-merge:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.3.1
        with:
          github-token: ${{secrets.GH_TOKEN_DEPENDABOT}}
