- name: Perform Scan
  uses: ShiftLeftSecurity/scan-action@master
  with:
    type: "credscan,javascrypt,ruby,html,depscan"
  env:
    WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SCAN_AUTO_BUILD: true
    
    - uses: actions/upload-artifact@v2.2.2
  with:
    name: reports
    path: reports
